Added new Features & Changed the graphs
PaddeCraft/KEGWeatherHist pull request #39
Opened 2024-03-16 23:34 UTC by NprogramDev

Every value now has its own graph
Tabs are now own sites
Added Program Versions in Information Tab
Added replaced and new parameter in Information Tab
Added switch for Dark and Light Mode, not implemented yet
Added Logo of PdCrNPrg.png
...

2024-03-17 10:58 UTC, PaddeCraft requested changes
See comments

2024-03-17 10:58 UTC, PaddeCraft commented on static/css/main.css
Is this reformatting necessary?

2024-03-17 10:58 UTC, PaddeCraft commented on static/js/tab5.js
Why is there an empty file?

2024-03-17 10:58 UTC, PaddeCraft commented on templates/base.html
Please use tailwind classes, e.g. `block` for display: block; and put the colors into the tailwind.config.js or look if there are default colors fitting here.

2024-03-17 10:58 UTC, PaddeCraft commented on templates/old.html
Why put the old version if we use git?

2024-03-17 17:50 UTC, NprogramDev commented on static/css/main.css
main.css is now the same as in the main branch

2024-03-17 17:54 UTC, NprogramDev commented on templates/base.html
The Green Color is not in the tailwind CSS, and I think it is not necessary, so you can change it if you want.

2024-03-18 18:44 UTC, PaddeCraft requested changes
Almost good, just a few small changes regarding inline styles and comments.

2024-03-18 18:44 UTC, PaddeCraft commented on templates/api_index.html
Please put the period in the python code, so that the URL isn't build in two locations.

2024-03-18 18:44 UTC, PaddeCraft commented on templates/base.html
> +            <div style="float: right;" class="flex h-[3rem] w-[5rem] justify-center mr-[1vw]">
Please add a comment clarifying that the inline css is required here.

2024-03-18 18:44 UTC, PaddeCraft commented on templates/live.html
> +<div class="js_enabled" style="display: none;" data-tab="0">
Is the inline style necessary here? If not, please use the tailwind `hidden`-class; else please add a comment clarifying the requirement of the inline style.

2024-03-18 18:44 UTC, PaddeCraft commented on templates/tabulator.html
> +            <a href="../live" style="text-decoration: none" class="tab tab-bordered tabsjs-sel" data-tab="0">Live&uuml;bersicht </a>
Please use tailwind classes instead of inline styles for all of these.

2024-03-18 18:44 UTC, PaddeCraft commented on templates/week.html
> +<div class="js_enabled" style="display: none;"  data-tab="2">
Please only use inline style if needed and if so, please add a comment clarifying the requirement.

2024-03-18 19:13 UTC, PaddeCraft approved these changes
LGTM

2024-03-18 19:14 UTC, merged